@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package com.junethewoods.myotherstuff.common.block.properties;

import mcp.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;